version: "3.1"

services:
  app:
    container_name: productservice-api
    image: product-service:0.0.1
    build: ./
    ports:
      - '8002:8002'
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    command: "mongod --port 27018"
    ports:
      - "27018:27018"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

